using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Medieval.Alchemy;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Imperial.Medieval.Alchemy;

[GenerateTypedNameReferences]
public sealed partial class AlchemyCoolingBathWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private bool _isProcessing;
    private int _selectedDuration;
    private TimeSpan _endTime;

    public event Action<int>? OnDurationSelected;

    public AlchemyCoolingBathWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(AlchemyCoolingBathUiState state)
    {
        _isProcessing = state.IsProcessing;
        _selectedDuration = state.SelectedDuration;
        _endTime = state.EndTime;
        DurationButtons.DisposeAllChildren();
        var group = new ButtonGroup();
        foreach (var duration in state.Durations)
        {
            var button = new Button
            {
                Text = duration.ToString(),
                TextAlign = Label.AlignMode.Center,
                ToggleMode = true,
                Group = group,
                Pressed = duration == state.SelectedDuration,
                HorizontalExpand = true,
                Disabled = state.IsProcessing,
            };
            button.StyleClasses.Add("OpenBoth");
            button.OnPressed += _ => OnDurationSelected?.Invoke(duration);
            DurationButtons.AddChild(button);
        }

        var disabled = state.IsProcessing || state.Contents.Length == 0;
        BusyOverlay.Visible = disabled;
        StartButton.Disabled = disabled || state.SelectedDuration <= 0;
        EjectButton.Disabled = disabled;
        ContentsPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(state.IsProcessing ? "#245A73" : "#1B1B1E"),
        };
        UpdateTimeLabel();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_isProcessing)
            UpdateTimeLabel();
    }

    private void UpdateTimeLabel()
    {
        var seconds = _isProcessing
            ? Math.Max(0, (int) Math.Ceiling((_endTime - _timing.CurTime).TotalSeconds))
            : _selectedDuration;
        TimeLabel.Text = Loc.GetString("alchemy-cooling-bath-timer", ("seconds", seconds));
    }
}
